### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by mnapoli** [jolicode/JoliCi#34]
Using the latest version (`dev-master` through Composer or the latest `phar`) I get the following error:

```
[GuzzleHttp\Exception\ServerException]
Server error response [url] /build?q=1&t=543b02a31d5da-php-5.3&nocache=0&rm=0 [status code] 500 [reason phrase] Internal Server Error
```

Above that, my console is flooded with PHP notices:

```
Notice: fwrite(): send of 5 bytes failed with errno=32 Broken pipe in phar:///myproject/jolici.phar/vendor/stage1/docker-php/src/Docker/Http/Adapter/DockerAdapter.php on line 96
```

I tried debugging, I moved into the temp directory and ran `docker build .` => it works (runs the tests just fine). By the way, the `travis.yml` is ultra basic. So it seems there's a problem connecting to docker.

I have installed Docker on OS X with boot2docker, using Homebrew. Docker works fine.

I also tried `jolici run --docker-host="tcp://192.168.59.103:2375"` but I get the same result (`$DOCKER_HOST` is correctly defined by the way).

Any idea?

**Comment by joelwurtz** [comment]
Closing as this should be good with last release

**Comment by joelwurtz** [comment]
Thanks for the report, don't hesite to reopen this issue if this error happens again
