### ISSUE TITLE
Scripts should be executed as user

### ISSUE THREAD

**Issue by clue** [jolicode/JoliCi#40]
Currently, all build steps are executed as user "root", whereas TravisCI uses a dedicated "travis" user. Also, TravisCI supports using `sudo` to switch to the root user, JoliCI does not.

This makes it quite difficult to explicitly execute build steps as user "root" (like installing software packages etc.). This *can* be worked around in the `.travis.yml` file, however it's [quite cumbersome](https://github.com/clue/php-ami-react/blob/ebe35f88e497a9bb0c2a87979b3f022e5608f14a/.travis.yml#L9).

Sample `.travis.yml` to reproduce:

```
language: php
php:
  - 5.5
install:
  - true # needed until PR #39 lands
script:
  - id -un
  - sudo id -un
```

Expected output (also supported by TravisCI):

```
travis
root
```

Actual output:

```
root
<< Exception trace >>

**Comment by joelwurtz** [comment]
Corrected in the images and the library, thanks for the report
