### ISSUE TITLE
Support passing DNS options

### ISSUE THREAD

**Issue by clue** [jolicode/JoliCi#46]
Each build will be run in a container that uses Docker's default DNS servers (Google's public DNS servers 8.8.8.8 and 8.8.4.4). Docker supports passing a `--dns` option for its `docker run` command, however JoliCi does not currently expose this option through its options.

Handing all DNS to Google's public DNS infrastructure might leak private information and might be an issue for those concerned about privacy.

More importantly I'm currently evaluating using JoliCi as part of our CI setup. One of our project uses an integration test that performs live queries against one of our internal servers hosted on `intranet.acme.com`. This server is not listed in our public DNS infrastructure, and can only be resolved via our local DNS server (10.0.0.1).

Arguably this feature might be out of scope because this address can't be resolved via the hosted Travis service either.

Given that adding support for the DNS option should be fairly straight forward, I figured it would be worth posting: Relevant place would be the [`Executor`](https://github.com/jolicode/JoliCi/blob/2641d0d7e3270330ee0921ca86a6f2ccea3008be/src/Joli/JoliCi/Executor.php#L139) and passing [`Dns` in the `$hostconfig`](https://docs.docker.com/reference/api/docker_remote_api_v1.15/#start-a-container).

**Comment by lyrixx** [comment]
Hello, 

Thanks for opening this issue.

Unfortunately, we don't support this repository anymore.
I'm sorry, but I'll close this issue.

I hope you understand.
