### ISSUE TITLE
missing pip

### ISSUE THREAD

**Issue by rande** [jolicode/JoliCi#48]
I am currently testing this joli projet for the sonata project and the default container is missing some tools available per default on travis. At least one tool: pip

See the SonataAdminBundle's travis file: https://github.com/sonata-project/SonataAdminBundle/blob/master/.travis.yml

**Comment by joelwurtz** [comment]
Hey,

Thanks for the report i add pip in all images to mimic travisci behavior in https://github.com/jolicode/docker-images/commit/38c9d62a3353dabfba84b998896d1446b42ce0fd

Images should be ready in a couple of minutes when they will be builded on docker hub registry. 

Be aware that you will need to manually delete or pull new version of all used images to get changes

```
docker pull jolicode/php53
docker pull jolicode/php54
...
```
