### ISSUE TITLE
Assume default versions for each language

### ISSUE THREAD

**Issue by clue** [jolicode/JoliCi#51]
Travis does not require an explicit definition of the version to test against, whereas JoliCi does. I noticed this in [one](https://github.com/clue/phar-composer/blob/master/.travis.yml) of my projects, the following `.travis.yml` should reproduce this:

```
language: php
```

```
PHP Notice:  Undefined index: php in phar:///usr/local/bin/jolici/src/Joli/JoliCi/BuildStrategy/TravisCiBuildStrategy.php on line 271
PHP Warning:  Invalid argument supplied for foreach() in phar:///usr/local/bin/jolici/src/Joli/JoliCi/BuildStrategy/TravisCiBuildStrategy.
php on line 273
PHP Catchable fatal error:  Argument 2 passed to Joli\JoliCi\Matrix::setDimension() must be of the type array, null given, called in phar:
///usr/local/bin/jolici/src/Joli/JoliCi/BuildStrategy/TravisCiBuildStrategy.php on line 303 and defined in phar:///usr/local/bin/jolici/sr
c/Joli/JoliCi/Matrix.php on line 26
```

Supporting this should be fairly straight forward, we just need to define a list of default versions for each language and fall back to this list if no other version is defined in the [`TravisCiBuildStrategy`](https://github.com/jolicode/JoliCi/blob/eea595866650f7372f2986eb95a30e0b46a568ea/src/Joli/JoliCi/BuildStrategy/TravisCiBuildStrategy.php#L271).

**Comment by joelwurtz** [comment]
Will be fixed in the next release thanks again for the report.
