### ISSUE TITLE
Quoted ENV variables do not work anymore

### ISSUE THREAD

**Issue by clue** [jolicode/JoliCi#52]
Quoted ENV variables used to work in 0.2.? and broke with 0.3.0.

`.travis.yml` as per [documentation](http://docs.travis-ci.com/user/environment-variables/#Variables-in-the-.travis.yml):

```yml
language: php
php:
- 5.5
env:
 - LOGIN='secret'
script:
 - echo $LOGIN
```

Expected output: `secret` (no quotes)
Actual output: `'secret'` (including quotes)

This will now pass the following instruction to Docker:

```
ENV LOGIN 'secret'
```

> The ENV instruction has two forms. The first form, ENV <key> <value>, will set a single variable to a value. The entire string after the first space will be treated as the <value> - including characters such as spaces and quotes.

https://docs.docker.com/reference/builder/#env

For the reference, noticed this in [one of my projects](https://github.com/clue/php-ami-react/blob/8cf23add9648cce1809ee647dcda9053dc096ed1/.travis.yml#L7).

**Comment by joelwurtz** [comment]
This will be fixed in the next release, thanks for the report !
