### ISSUE TITLE
Possible to embed "travis_retry" internal tool?

### ISSUE THREAD

**Issue by wysow** [jolicode/JoliCi#55]
As stated in the title, it would be great to be able to use the `travis_retry` tool... What do you think?

**Comment by joelwurtz** [comment]
Great idea, in fact for better integration i would like to use the travis build script, which would generate also the travis retry function, but i don't know if this will work weel as our environments try to mimic travis ci one but are not perfectly equal.

**Comment by clue** [comment]
See also https://github.com/jolicode/docker-images/issues/8

**Comment by lyrixx** [comment]
Hello, 

Thanks for opening this issue.

Unfortunately, we don't support this repository anymore.
I'm sorry, but I'll close this issue.

I hope you understand.
