### ISSUE TITLE
JoliCi phar URL is broken

### ISSUE THREAD

**Issue by chadrien** [jolicode/JoliCi#56]
From `https://github.com/jolicode/JoliCi/blob/master/docs/installation.md`:

```
curl http://jolici.jolicode.com/jolici.phar -o /usr/local/bin/jolici
```

But `http://jolici.jolicode.com/jolici.phar` actually redirects to the Jolicode website.
Not that we don't like it, it's beautiful and shiny (probably thanks to a unicorn powered core) but what we really want is your awesome phar file :wink:

**Comment by joelwurtz** [comment]
Hello,

Thanks for pointing this out, was planning to create this sub domain with last version, but never got the time, i fix the url where the phar can be download in the install doc.

Happy Testing :)
