### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by splitice** [jolicode/JoliCi#57]
It might be a good idea to write a getting started guide, or a step by step tutorial on how to get this running.

Perhaps take advantage of the Digitalocean article bounties program and write a getting started for Digital Ocean for starters?

**Comment by lyrixx** [comment]
Hello, 

Thanks for opening this issue.

Unfortunately, we don't support this repository anymore.
I'm sorry, but I'll close this issue.

I hope you understand.
