### ISSUE TITLE
Exception occurs if using docker 1.7.0

### ISSUE THREAD

**Issue by thklein** [jolicode/JoliCi#58]
Jolici throws an exception when using it with docker version 1.7.0!
With an older version e.g. 1.6.2 it's all fine.

![exception](https://cloud.githubusercontent.com/assets/4243826/8614246/124ce3c2-26e8-11e5-8dd4-e4ab0e6aebeb.png)

**Comment by clue** [comment]
Same error here. Latest JoliCI release on Ubuntu 14.04 LTS.
Worked fine up until Docker v1.6.2, broke with Docker v1.7.0

**Comment by beberlei** [comment]
I have this error as well.

**Comment by joelwurtz** [comment]
This should be good with the PR from @beberlei, but there may be same issues coming from this bug :   https://github.com/stage1/docker-php/issues/122

**Comment by thunderer** [comment]
I also confirm the error, Docker 1.8.1, Ubuntu 15.04, latest JoliCI.

**Comment by KimPeeters** [comment]
I also confim the error.
Docker version 1.11.1, build 5604cbe
jolici version 0.3.1

**Comment by lyrixx** [comment]
Hello, 

Thanks for opening this issue.

Unfortunately, we don't support this repository anymore.
I'm sorry, but I'll close this issue.

I hope you understand.
