### ISSUE TITLE
Add scala support

### ISSUE THREAD

**Issue by agur** [jolicode/JoliCi#64]
Currently getting an exception when trying to use on a scala project locally.

   [Exception]  
  Language scala not supported

**Comment by amirgur1** [comment]
@joelwurtz - is that easy to add?

**Comment by joelwurtz** [comment]
Actually there is no image to handle Java/Scala (see https://github.com/jolicode/JoliCi/blob/master/docs/strategies/TravisCiStrategy.md), for adding this support the first step is to add the Dockerfile which will mimic travis ci environnement on this repository : https://github.com/jolicode/docker-images and then add the corresponding mapping into JoliCi

If you know how is installed java on travis ci environment and if there is already images hanling this in docker hub this can be helpful

**Comment by agur** [comment]
Thanks Joel,
Official Docker repo for java: https://hub.docker.com/_/java/, then on github: https://github.com/docker-library/java.Hope that helps - let me know if anything else is needed.
Thanks, Amir

**Comment by lyrixx** [comment]
Hello, 

Thanks for opening this issue.

Unfortunately, we don't support this repository anymore.
I'm sorry, but I'll close this issue.

I hope you understand.
