### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by d33tah** [jolicode/JoliCi#66]
I noticed that this project hadn't been touched since September. What's its status?

**Comment by joelwurtz** [comment]
Hey,

It's status is currently waiting on some features from the docker-php library which will be only usable with a new http client (for async reason).

I'm heavily participing on this by contributiting to these projects : https://github.com/php-http. I'm also writing these libs : https://github.com/jolicode/jane and https://github.com/jolicode/jane-swagger which will help to support recent versions of dockers without too much maintenance.

My plan is to finish these dependencies by the month of november / december and beginning to write new features and better support for services to JoliCi in beginning of 2016.

Anyway any help is welcome :)
