### ISSUE TITLE
Missing travis user in Docker container

### ISSUE THREAD

**Issue by satreix** [jolicode/JoliCi#67]
Hi JoliCi,

I wanted to try you out but I got the following error:

```
Creating builds...
1 builds created

Running job ruby = 2.1.0

Step 1 : FROM jolicode/ruby-2.1.0:latest
 ---> 50efffbf16af
Step 2 : ENV WORKDIR $HOME/project
 ---> c404dbd9f5d3
Step 3 : ADD . $WORKDIR
 ---> 9e12c31dfd32
Step 4 : WORKDIR $HOME/project
 ---> 3905da34f8db
Step 5 : RUN sudo chown travis:travis -R $HOME/project
 ---> Running in 3a087983be11
chown: invalid user: `travis:travis'

Error when creating job: The command returned a non-zero code: 1
'/bin/sh -c sudo chown travis:travis -R $HOME/project'
```

I guess it is due to _resources/templates/Dockerfile.twig_ on line 11, would a simple `useradd` solve this issue like so?

``` dockerfile
RUN sudo useradd travis
```

I tried editing the _.phar_ directly but, you guessed it, php stopped my from executing a _corrupted_ (get manuallly edited) file.

**Comment by dmacvicar** [comment]
I encountered the same problem. I rebuilt the images from https://github.com/jolicode/docker-images locally:

```console
git clone https://github.com/jolicode/docker-images
make ruby193 ruby210
```

And I did not had the problem anymore. I suspect the authors haven't pushed the current images to the hub.

**Comment by satreix** [comment]
A did not use this project anymore. Closing.
