### ISSUE TITLE
Contributing new languages guidelines

### ISSUE THREAD

**Issue by Chris7** [jolicode/JoliCi#68]
I'd like to add Python support to this. From a quick perusal, it appears the steps would be:

1) Make python .twig files in resources/templates/python
2) Add python to the TravisCIBuildStrategy.php with relevant values (in $defaults)
3) Create python docker files here: https://github.com/jolicode/docker-images

Am I missing any steps? I think documenting this well would lead to others filling in the gaps with language coverage as their own needs arose.

**Comment by joelwurtz** [comment]
This should be good with these step

> 1) Make python .twig files in resources/templates/python

Be aware that format for Dockerfile must be like the folliwing : resources/templates/python/Dockerfile-2.7 for version 2.7 in travis file or resources/templates/python/Dockerfile-3.0 for version 3.0 in travis file

> 2) Add python to the TravisCIBuildStrategy.php with relevant values (in $defaults)

Don't hesite to read / search for travis default (really don't know how there python env is, but maybe they use `pip` as the default package manager ?)

> 3) Create python docker files here: https://github.com/jolicode/docker-images

Try to be as close as travis environment, this require reading many files in there chef cookbook here https://github.com/travis-ci/travis-cookbooks, it's the most difficult part when adding a new language to JoliCi as user expect to have similar environment.

However don't try to be 100% compliant with travis as it can be a pain in the ass sometimes (containers are not vm), you should focus on a 99% compatibility.

Don't hesitate to comment on this issue if you encounter any bug or have any question, so i can use this as a base for the documentation.

Good luck :)

**Comment by splitice** [comment]
I would love some documentation on this. Within the next 3 - 12 months I am thinking of working on a CSharp & C container. Basically to take over for a project currently costing me nothing due to the Student Pack.

Realistically what kind of time estimate do you think is involved in this?
Asside from some minor environment changes, its mainly the installation of packages right?
Perhaps it would be good if there was a base docker image w/o any php / ruby environment to start from with JoliCI?

**Comment by lyrixx** [comment]
Hello, 

Thanks for opening this issue.

Unfortunately, we don't support this repository anymore.
I'm sorry, but I'll close this issue.

I hope you understand.
