### ISSUE TITLE
APIExecption on build

### ISSUE THREAD

**Issue by angezanetti** [jolicode/JoliCi#70]
Hey guys, 

I tried to build my Silex project with JoliCI, i installed the .phar with the wget command.

My .travis.yml is:

```
language: php
php:
  - '5.5'
```
When i run the `php jolici.phar run -v` it returns two errors:

> [Docker\Exception\APIException]                               
>   json: cannot unmarshal object into Go value of type []string 

> [GuzzleHttp\Exception\ServerException]                                                                        
>   Server error response [url] /containers/create?name= [status code] 500 [reason phrase] Internal Server Error 

I pasted the full trace here : https://framabin.org/?a0e27731df1fc151#4+VuYHvZxFrabzJnObpCDH963D2/W391oLGUu649Z8o=

I search for similar issues on the web, it seems to be some known issue of docker-php but i can't figure out how i can fix this for JoliCI.

Any tips ?

**Comment by joelwurtz** [comment]
Yes it's a bug from previous releases of docker-php where the phar is still associated to. I intend to update jolici with the stable release of docker-php this week or the one after.

If you use the master version of this branch there is a fix, on that also (you can require jolici on dev-master with global from composer)

**Comment by angezanetti** [comment]
Thanks !

I use the composer command with the dev-master branch, 
launch the build with `php vendor/jolicode/jolici/bin/jolici run -v` and i got a Successfull Build !
