### ISSUE TITLE
PHPUnit requires PHP 5.6

### ISSUE THREAD

**Issue by angezanetti** [jolicode/JoliCi#71]
When i try to build my project with PHP 5.5 in my .travis.yml the build is successfull but it returns 

`This version of PHPUnit requires PHP 5.6; using the latest version of PHP is highly recommended.
`
With 5.6 it works fine.

I see there is a similar issue on travis :https://github.com/travis-ci/travis-ci/issues/5206, i tried to add the `before_install` instruction but it did not works for me…

**Comment by lyrixx** [comment]
Hello, 

Thanks for opening this issue.

Unfortunately, we don't support this repository anymore.
I'm sorry, but I'll close this issue.

I hope you understand.
