### ISSUE TITLE
services: mysql

### ISSUE THREAD

**Issue by jakubpas** [jolicode/JoliCi#74]
In my .travis.yml I have mysq service:

```
services:
  - mysq
```

After run JoliCi see errors:

> [Docker\Exception\APIException]  
>   No such image: mysql:5.5 
> 
> [Docker\Exception\APIException]  
>   No such image: mysql:5.5  
> [GuzzleHttp\Exception\ClientException]  
>   Client error response [url] /images/mysql%3A5.5/json [status code] 404 [reason phrase] Not Foun

Am I douing anything wrong or is there a bug?

**Comment by lyrixx** [comment]
Hello, 

Thanks for opening this issue.

Unfortunately, we don't support this repository anymore.
I'm sorry, but I'll close this issue.

I hope you understand.
